name: mlflow-env

channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - pip:
      - mlflow==2.17.2
      - pandas
      - numpy
      - scikit-learn
      - cloudpickle
      - joblib
