name: MLflow CI Pipeline

on:
  push:
    branches:
      - master
      - main

jobs:
  retrain-model:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow pandas numpy scikit-learn joblib

      - name: Check repository structure
        run: |
          pwd
          ls
          find . -maxdepth 2 -type f

      - name: Run MLflow project
        run: |
          mlflow run .
